### ISSUE TITLE
(node:10368) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated. 

### ISSUE THREAD

**Issue by reckertz** [PiXy79/pdf2images#1]
Great tool. The message is caused by fs.unlink(imageFilepath); and fs.unlink(fileName);
Please change it to fs.unlinkSync(imageFilepath) and fs.unlinkSync(fileName); and the Warning will not show up

**Comment by ehsunshahid** [comment]
Still waiting for this issue to be fixed

**Comment by yingzha15** [comment]
Hi @PiXy79 could you please fix the issue? The tool doesn't work on node 10.x.x due to the same issue : TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. at pdf2images.js:73:8. The change suggested above should fix it.

**Comment by ehsunshahid** [comment]
@yingzha15 i believe the developer is not actively working on it, i would suggest you to load the code on ur local machine and make that ammend on your own, that is what i did. Or if u want the updated code, i can provide u one.

**Comment by PiXy79** [comment]
Thanks @ehsunshahid, I've merged your pull request.
